### ISSUE TITLE
[Intro to iOS] Project 3/Week 3 - Twitter client complete

### ISSUE THREAD

**Issue by aamays** [aamays/Twitter#1]
My app is complete, please review /cc @codepathreview

**Comment by codepathreview** [comment]
I couldn't get your app to login, even with a different set of key and secret. Could you update your readme with instructions?

**Comment by aamays** [comment]
Hi /cc @codepathreview,

Actually I just realized that I have not checked in my key values in my  CredentialsInfo.plist file.

https://github.com/aamays/Twitter/blob/master/Twitter/CredentialsInfo.plist

Sorry about that. Let me do it right away.

Thanks!
Amay

**Comment by aamays** [comment]
Hi /cc @codepathreview,

I have updated my  CredentialsInfo.plist with App key and secret. It should be good to go now.

https://github.com/aamays/Twitter/commit/acdebb73288119b5380bcf2c16d36a315839a6b8

Thanks!
Amay

**Comment by aamays** [comment]
Hi /cc @codepathreview,

I have updated README.md with the instructions on setting up the credentials for the app to work.

I also tested the application with brand new set of keys and on a fresh simulator device and it is working fine.

Please let me know if you are still having issues logging in.

Thanks!
Amay

**Comment by codepathreview** [comment]
thanks! That worked. It is always easiest for me to have the most minimal installation instructions, having to review 28 apps...

awesome app btw

-- dirk

**Comment by aamays** [comment]
Hi Dirk,

I will make sure to include installation instructions in my future submission (whenever required).

And I am glad that you liked my submission. Thanks!
- Amay

**Comment by codepathreview** [comment]
:+1: nice work. The point of this homework was to explore a simple example of a full MVC application with a RESTful API. For each point in the homework feedback checklist, I'll either confirm that you're on the right track with the implementation, or I'll provide some feedback:
- You should declare all unnecessarily public properties as private for better encapsulation.
- Nice work specifying the Auto Layout constraints.
- Note that you should try handling the conditionally present retweet label in the cells. This is a situation where its not possible to specify the behavior that you want solely using Interface Builder.
- Nice work setting up the controls within the Tweet cells. It can sometimes be hard to have a clean design for embedded controls because it usually involves cumbersome plumbing. This is an instance where I think having the model handle the network action helps greatly simplify the implementation.
- Nice work handling the post tweet insertion into the feed. In real MVC apps, the more polished experiences have to do a certain amount of local object management to make a fully seamless experience, great seeing you use `reloadRowsAtIndexPaths`

In general, you should challenge yourself to create visually polished applications. That's where you'll find all the rough edges of the iOS framework and earn the next level of mastery.

-- dirk

**Comment by aamays** [comment]
Hi Dirk (/cc @codepathreview),

Thank you for reviewing my app and I really appreciate all your feedback. I will incorporate your suggestions as enhancement to this app and will keep them in mind while developing apps in future.

Thanks again!
Amay
